### ISSUE TITLE
Need some help!

### ISSUE THREAD

**Issue by 17k3eujs** [SinglePageBookProject/SPB#1]
Hey! Saw your project and it looks interesting!

I followed the instructions in your micro how to [here](https://singlepagebookproject.github.io/Single-Page-Book/README.html) and when i tested it, it does not seem to be interacting with anything besides hover. 

In your examples such as [this](http://www.oficina24x7.com/JAVA/java_map.html) I can double click to bring up detailed information.

Is there something i am doing wrong here? Help would be appreciated.

**Comment by earizon** [comment]
Just take a look at relative paths  (value of src="..." for map_v1.js and map_v1.css).

It could be the case that you just need ./map_v1.js (instead of ./IT_notes/map_v1.js) for example. This can slightly vary depending on your local setup.

You can use your desktop browser to trace the origin of the problem. E.g, on Firefox just press F12  to open Development Tools,  then click on tab "network". If the relative route to map_v1.js or map_v1.css is not correct the error will be printed out. 
Put attention also to any weird error in the console tab.
